### PR TITLE
Add background script for client on Windows

### PR DESCRIPTION
**Pull request by koczadly**
Adds an extra script for running the client in the background on Windows & other misc fixes.

Might be a good idea to also issue a new release (zip) with these changes.

### CODE REVIEW

**Comment by guilhermelawless** [comment]
Great idea, will review in the upcoming days. Thanks @koczadly !

**Comment by koczadly** [comment]
@Joohansson Just tried it (and pushed a commit), but it seems to fail on my device:
```Traceback (most recent call last):
  File "dpow_client.py", line 10, in <module>
    from hbmqtt.client import MQTTClient, ClientException, ConnectException
ModuleNotFoundError: No module named 'hbmqtt'```

Original command worked fine though. Not sure if I'm missing something?

**Comment by koczadly** [comment]
Nevermind, it was an issue on my end. Had 2 versions of Python 3 installed, and pip was being weird.

**Comment by Joohansson** [comment]
> Nevermind, it was an issue on my end. Had 2 versions of Python 3 installed, and pip was being weird.

Yeah I did the same mistake. Had to run pip from the actual python version

**Pull request merged**
